Added larch normalization scheme to postprocessing
AI-multimodal/aimmdb pull request #48
Opened 2022-11-02 17:10 UTC by CharlesC30

Created new class for larch normalization scheme in operations module. Also added testing for new operator in tutorial notebook.

2022-11-02 19:25 UTC, CharlesC30 commented
@x94carbone

2022-11-02 21:00 UTC, x94carbone requested changes
Looks really solid, thank you. Few changes are requested!

2022-11-02 21:00 UTC, x94carbone commented on aimmdb/postprocessing/operations.py
> +    def flatten(group: xafsgroup):
Should be a "private" method, i.e. `_flatten` not `flatten`.

2022-11-03 16:53 UTC, x94carbone requested changes
@CharlesC30 looks good, but I still think that `_process_data` could use some documentation. It would just be nice to know what Larch is doing to some degree. Actually, it might be best to put this in the doctoring for `NormalizeLarch`. Don't waste more than a day trying to figure out exactly what it's doing, worst case we just use it as is and don't worry about it 😁

2022-11-03 18:57 UTC, CharlesC30 commented
@x94carbone I added an explanation of the normalization process in larch to the `NormalizeLarch` docstring. Some of it is copied from the larch source code then modified slightly for how we are using it here.

2022-11-03 19:15 UTC, CharlesC30 commented
Also if we wanted to we could add more parameters to this class to interface with larch more. 
For example there could be a keyword argument `e0` (default equal to `None`), that is also given to the larch `pre_edge` function during normalization. 
This could also be done for other keyword arguments in the `pre_edge` function. Though I am not sure if this is how we want these operators to work.

2022-11-03 19:59 UTC, x94carbone commented
@CharlesC30 perhaps just add a ``**kwargs`` arg to the init or something like that?

2022-11-04 04:08 UTC, CharlesC30 commented
> @CharlesC30 perhaps just add a `**kwargs` arg to the init or something like that?

good idea! added

2022-11-04 12:06 UTC, x94carbone approved these changes
Looks good! @CharlesC30 is this still a work in progress or are you good to merge?

2022-11-04 14:58 UTC, CharlesC30 commented
> I like this. That would be part of forcing the Larch normalization parameters, right?

@x94carbone yeah exactly! By default larch calculates most parameters itself but we could explicitly pass things that are already known.

> Give it some thought, let me know what you think! The general idea is that the operator would take these types of parameters during instantiation. Then the `__call__` method just takes what's being operated on.

Okay I think it's not a bad idea then. I was looking at the other operators though and think maybe we should use the same approach as the `StandardizeGrid` operator. Basically provide a dict keyword argument to the `__init__` that contains all the larch `pre_edge` kwargs, then link to the `pre_edge` documentation in our docstring.

2022-11-04 15:16 UTC, x94carbone commented
@CharlesC30 Yep this is really good, great work, thank you! Basically exactly what I was looking for. I think this PR is good to go unless you have any other suggestions.

2022-11-04 15:17 UTC, CharlesC30 commented
@x94carbone All good with me! I think it's okay to merge

2022-11-04 15:33 UTC, merged